
version: '3'

services:
  mongo-express:
          image: mongo-express
          container_name: mongo-express
          ports:
              - 8081:8081
          volumes:
              - ./.docker/volumeMongoExpress/docker-entrypoint.sh:/docker-entrypoint.sh
          env_file:
              - .env
          environment:
              ME_CONFIG_MONGODB_SERVER: mongodb
              ME_CONFIG_MONGODB_ADMINUSERNAME: root
              ME_CONFIG_MONGODB_ADMINPASSWORD: 123
              ME_CONFIG_BASICAUTH_USERNAME: root
              ME_CONFIG_BASICAUTH_PASSWORD: 123
          depends_on:
              - mongodb
          networks:
            - mongo-compose-network

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/volumeMongo:/data/db
    networks:
      - mongo-compose-network



networks: 
    mongo-compose-network:
      driver: bridge